### ISSUE TITLE
0.999.9 panics

### ISSUE THREAD

**Issue by libr2** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#33] opened 2024-01-20 14:38 UTC
everything works perfectly except that my phone keeps panicking from 1 to 4 hours after jailbreaking.
also thank u again for ur efforts and contributions to keep the jailbreak community alive! <3

**Comment by KpwnZ** [comment] 2024-01-20 19:19
I think I already know the reason now. Working on it now!

**Comment by Pwn0day** [comment] 2024-01-20 19:30
> I think I already know the reason now. Working on it now!

can you support the 16.6+ this time please.

**Comment by KpwnZ** [comment] 2024-01-20 20:39
It's been 8 hours since last panic now. I am still testing it.

**Comment by libr2** [comment] 2024-01-20 21:37
> It's been 8 hours since last panic now. I am still testing it.

sounds like good news!!

**Comment by KpwnZ** [comment] 2024-01-21 02:00
I feel like it's fixed now. I haven't encountered any panic yet. But I will do more test to confirm.

**Comment by KpwnZ** [comment] 2024-01-21 04:26
> I feel like it's fixed now. I haven't encountered any panic yet. But I will do more test to confirm.

Ok now I guess I can confirm it's fixed. I have tested with high computational demanding tasks, lock screen, and used as daily device and there is no panic.

**Comment by Pwn0day** [comment] 2024-01-21 04:29
> > I feel like it's fixed now. I haven't encountered any panic yet. But I will do more test to confirm.
> 
> Ok now I guess I can confirm it's fixed. I have tested with high computational resource demanding tasks, lock screen, and used as daily device and there is no panic.

you ignore my reply.

**Comment by KpwnZ** [comment] 2024-01-21 04:40
> > > I feel like it's fixed now. I haven't encountered any panic yet. But I will do more test to confirm.
> 
> > 
> 
> > Ok now I guess I can confirm it's fixed. I have tested with high computational resource demanding tasks, lock screen, and used as daily device and there is no panic.
> 
> 
> 
> you ignore my reply.

Issue is for tracking specific problems. Keep it clean.

**Comment by KpwnZ** [comment] 2024-01-21 05:03
New version is available now. https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.10New version is available now. https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.10

**Comment by michaelmelita1** [comment] 2024-01-21 07:04
I can also confirm my iPhone X 16.5 has been running perfectly fine for the last 2 hours. Has never been able to stay this long in the jailbroken state. Out of curiosity what was the issue

**Comment by KpwnZ** [comment] 2024-01-21 07:29
> I can also confirm my iPhone X 16.5 has been running perfectly fine for the last 2 hours. Has never been able to stay this long in the jailbroken state. Out of curiosity what was the issue

IPC port was not cleaned properly.

**Comment by libr2** [comment] 2024-01-21 14:18
> > I can also confirm my iPhone X 16.5 has been running perfectly fine for the last 2 hours. Has never been able to stay this long in the jailbroken state. Out of curiosity what was the issue
> 
> IPC port was not cleaned properly.

btw i just noticed that the webkit not working/loading pages at all for some reason? 

https://drive.google.com/file/d/1EB_hrhsD80x9yXMbIhvrqH73siA6Y100/view?usp=drivesdk

https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/157130969/940983fe-af46-4251-b2da-7445bc92d58f

**Comment by KpwnZ** [comment] 2024-01-21 15:13
> > > I can also confirm my iPhone X 16.5 has been running perfectly fine for the last 2 hours. Has never been able to stay this long in the jailbroken state. Out of curiosity what was the issue
> > 
> > IPC port was not cleaned properly.
> 
> btw i just noticed that the webkit not working/loading pages at all for some reason? 
> 
> https://drive.google.com/file/d/1EB_hrhsD80x9yXMbIhvrqH73siA6Y100/view?usp=drivesdk
> 
> https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/157130969/940983fe-af46-4251-b2da-7445bc92d58f

Open a new issue please.

**Closed** 2024-01-21 19:02 UTC
Labels: bug
